# Generated by Django 5.2.1 on 2025-05-16 04:44

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('LeaveTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('LeaveTypeName', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('Slotid', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('YearID', models.AutoField(primary_key=True, serialize=False)),
                ('YearName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('Batchid', models.AutoField(primary_key=True, serialize=False)),
                ('BatchName', models.CharField(default='Batch', max_length=50)),
                ('class_id', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='DepartmentID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('HODID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(max_length=255, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PRN', models.CharField(default='102012', max_length=255)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('MobileNumber', models.CharField(max_length=255, unique=True)),
                ('RollNumber', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('batch', models.IntegerField(default=1)),
                ('CurrentClassID', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('RoleID', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('FeeID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ReceivedAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial')], max_length=50)),
                ('DueDate', models.DateField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('AlumniID', models.AutoField(primary_key=True, serialize=False)),
                ('GraduationDate', models.DateField()),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('ContactNumber', models.CharField(max_length=255, unique=True)),
                ('LastClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgression',
            fields=[
                ('ProgressionID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Status', models.CharField(choices=[('Current', 'Current'), ('Completed', 'Completed'), ('Year Down', 'Year Down')], max_length=50)),
                ('YearDownReason', models.TextField(blank=True, null=True)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=255)),
                ('SubjectSemester', models.IntegerField()),
                ('SubjectBatch', models.CharField(max_length=255)),
                ('SubjectYear', models.CharField(default='none', max_length=255)),
                ('SubjectType', models.BooleanField(default=True, max_length=50)),
                ('SubjectDepartment', models.CharField(default='none', max_length=255)),
                ('CurrentClassID', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('Subjectdep', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('Subjectyr', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.year')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False)),
                ('Marks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('BacklogID', models.AutoField(primary_key=True, serialize=False)),
                ('BacklogDate', models.DateField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared')], max_length=50)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(default='DEFAULT_SUBJECT_NAME', max_length=50)),
                ('Date', models.DateField()),
                ('Timeto', models.CharField(default='DEFAULT_TIME', max_length=50)),
                ('Timefrom', models.CharField(default='DEFAULT_TIME', max_length=50)),
                ('Status', models.BooleanField(max_length=50)),
                ('ClassID', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('SlotID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.slots')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('SubjectID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacherid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(max_length=255, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('attachment', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('teacherpublished', models.ForeignKey(default=uuid.UUID('45d8c03d-0e93-48a7-b036-41ad381b7233'), on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('LeaveRequestID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Reason', models.TextField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Pending Principal Approval', 'Pending Principal Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('RequestDate', models.DateTimeField(auto_now_add=True)),
                ('ApprovalDate', models.DateTimeField(blank=True, null=True)),
                ('is_approvedByHOD', models.BooleanField(default=False)),
                ('is_approvedByPrincipal', models.BooleanField(default=False)),
                ('HODApprovalDate', models.DateTimeField(blank=True, null=True)),
                ('PrincipalApprovalDate', models.DateTimeField(blank=True, null=True)),
                ('LeaveTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
                ('RequestedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvals', to='api.teacher')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TempTimetable',
            fields=[
                ('TimeSlotID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('LeaveRequestID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.leaverequest')),
                ('ReplacementTeacherID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.teachersubjectassignment')),
                ('SlotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.slots')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('TimetableID', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.CharField(default='Monday', max_length=255)),
                ('Batch', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('SlotID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.slots')),
                ('SubjectAssignmentID', models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='api.teachersubjectassignment')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='YearID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.year'),
        ),
    ]
