# Generated by Django 5.2.1 on 2025-05-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Day',
            field=models.CharField(db_index=True, default='Monday', max_length=255),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['Day', 'SubjectAssignmentID'], name='api_timetab_Day_6d8414_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['ClassID', 'SlotID'], name='api_timetab_ClassID_1d7017_idx'),
        ),
    ]
