# Generated by Django 5.2.1 on 2025-05-20 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notice_noticedocument_delete_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='class_id',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classes'),
        ),
    ]
