# Generated by Django 5.2.1 on 2025-06-02 11:06

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notice_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='default_allocation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('leave_balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('allocated', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('year', models.IntegerField(default=api.models.get_current_year)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='api.teacher')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'leave_type', 'year'], name='api_employe_employe_4c29dc_idx')],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
