# Generated by Django 5.2.1 on 2025-06-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_leavetype_default_allocation_employeeleavebalance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeLeaveBalance',
            new_name='TeacherLeaveBalance',
        ),
        migrations.RenameIndex(
            model_name='teacherleavebalance',
            new_name='api_teacher_employe_e3a3d7_idx',
            old_name='api_employe_employe_4c29dc_idx',
        ),
    ]
